name = "feats-api"
main = "src/index.js"
compatibility_date = "2026-06-05"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "feats-images"

[[d1_databases]]
binding = "DB"
database_name = "feats-db"
database_id = "af52488d-a2d2-4a58-9c67-772621a342cd"
