name = "feats-live"
main = "src/index.js"
compatibility_date = "2026-06-05"

routes = [{ pattern = "feats-live.louishitchcock.xyz", custom_domain = true }]

[[kv_namespaces]]
binding = "admin_html"
id = "57ea96e73dca4316b39881eccf4e6279"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "feats-images"

[[d1_databases]]
binding = "DB"
database_name = "feats-db"
database_id = "af52488d-a2d2-4a58-9c67-772621a342cd"
